module.exports.names = [
    "The Midnight Sky",
    "Wonder Woman 1984",
    "Soul",
    "Tenet",
    "The Trial of the Chicago 7",
    "The Father",
    "The Dig",
    "Nomadland",
    "Mank",
    "Ma Rainey's Black Bottom",
    "Promising Young Woman",
    "Minari",
    "Pieces of a Woman",
    "The White Tiger",
    "Judas and the Black Messiah",
    "Sound of Metal",
    "The Mauritanian",
    "The Little Things",
    "Cherry",
    "News of the World",
    "I Care a Lot",
    "The Courier",
    "The Marksman",
    "The King's Man",
    "Zack Snyder's Justice League",
    "Coming 2 America",
    "Raya and the Last Dragon",
    "The SpongeBob Movie: Sponge on the Run",
    "Mortal Kombat",
    "The Suicide Squad",
    "Cruella",
    "Tom & Jerry",
    "Godzilla vs. Kong",
    "Black Widow",
    "No Time to Die",
    "F9",
    "A Quiet Place Part II",
    "Top Gun: Maverick",
    "Dune",
    "Free Guy",
    "The Matrix Resurrections",
    "Ghostbusters: Afterlife",
    "The French Dispatch",
    "West Side Story",
    "Space Jam: A New Legacy",
    "The Last Duel",
    "Shang-Chi and the Legend of the Ten Rings",
    "Eternals",
    "Venom: Let There Be Carnage",
    "The Batman",
    "Spider-Man: No Way Home",
    "The Matrix Resurrections",
    "The Adam Project",
    "Bullet Train",
    "The Northman",
    "Ambulance",
    "Black Crab",
    "Don't Look Up",
    "Armageddon Time",
    "Red Notice",
    "The Woman in the Window",
    "The Tomorrow War",
    "Beckett",
    "Escape Room: Tournament of Champions",
    "Old",
    "The Forever Purge",
    "The Tomorrow War",
    "The Ice Road",
    "Wrath of Man",
    "The Unforgivable",
    "The Contractor",
    "The Marksman",
    "The Protege",
    "Infinite",
    "Reminiscence",
    "No Sudden Move",
    "The Card Counter",
    "The Green Knight",
    "Annette",
    "The Power of the Dog",
    "The Lost Daughter",
    "Belfast",
    "The Eyes of Tammy Faye",
    "tick, tick... BOOM!",
    "Passing",
    "C'mon C'mon",
    "CODA",
    "Spencer",
    "Titane",
    "Drive My Car",
    "The Worst Person in the World",
    "Benedetta",
    "The Hand of God",
    "A Hero",
    "A Chiara",
    "The Power of the Dog",
    "The Lost Daughter",
    "Belfast",
    "The Eyes of Tammy Faye",
    "tick, tick... BOOM!",
    "Passing",
    "C'mon C'mon",
    "CODA",
    "Spencer",
    "Titane",
    "Drive My Car",
    "The Worst Person in the World",
    "Benedetta",
    "The Hand of God",
    "A Hero",
    "A Chiara"
]

module.exports.ratings = [
    6.0,
    5.4,
    8.1,
    7.5,
    7.8,
    6.9,
    7.2,
    8.5,
    6.3,
    7.0,
    6.8,
    7.1,
    8.0,
    6.5,
    7.3,
    6.7,
    7.6,
    8.3,
    5.9,
    7.4,
    6.2,
    6.6,
    7.9,
    5.8,
    7.7,
    8.2,
    6.4,
    6.1,
    8.4,
    6.0,
    5.5,
    7.5,
    7.2,
    8.1,
    7.0,
    7.8,
    6.9,
    7.6,
    6.8,
    8.0,
    7.3,
    7.1,
    8.2,
    7.4,
    7.7,
    7.9,
    8.3,
    7.2,
    8.5,
    7.6,
    8.4,
    8.0,
    7.8,
    7.5,
    8.1,
    7.3,
    8.2,
    7.7,
    8.6,
    7.9,
    8.3,
    7.4,
    8.0,
    7.6,
    8.5,
    7.2,
    8.1,
    7.9,
    8.4,
    7.7,
    8.2,
    7.8,
    8.3,
    7.5,
    8.0,
    7.3,
    8.1,
    7.6,
    8.2,
    7.9,
    8.4,
    7.7,
    8.3,
    7.8,
    8.5,
    7.2,
    8.0,
    7.5,
    8.1,
    7.4,
    8.2,
    7.7,
    8.3,
    7.6,
    8.4,
    7.9,
    8.5,
    7.8,
    8.0,
    7.3,
    8.1,
    7.7
];

module.exports.descriptions = [
    "A post-apocalyptic tale, in which a lone scientist in the Arctic races to stop a group of astronauts from returning home to a mysterious global catastrophe.",
    "Rewind to the 1980s as Wonder Woman's next big-screen adventure finds her facing two all-new foes: Max Lord and The Cheetah.",
    "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself.",
    "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    "The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago, Illinois.",    
    "A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind, and even the fabric of his reality.",    "An archaeologist embarks on the historically important excavation of Sutton Hoo in 1938.",
    "After losing everything in the Great Recession, a woman embarks on a journey through the American West, living as a van-dwelling modern-day nomad.",
    "1930s Hollywood is re-evaluated through the eyes of scathing social critic and alcoholic screenwriter Herman J. Mankiewicz as he races to finish the screenplay of Citizen Kane.",
    "Chicago, 1927. A recording session. Tensions rise between Ma Rainey, her ambitious horn player, and the white management determined to control the uncontrollable 'Mother of the Blues'. Based on Pulitzer Prize winner August Wilson's play.",    
    "A Civil War veteran teams up with a Union soldier to free his enslaved wife from a brutal plantation owner in Mississippi.",
    "In 1800s England, a young woman follows her heart and defies societal expectations by falling in love with a wealthy landowner.",
    "A young woman discovers she has the power to control time and must use it to save her family from a sinister force.",
    "A group of friends embarks on a perilous journey through a fantasy realm to defeat an evil sorcerer and save their kingdom.",
    "In a dystopian future where society is divided into factions based on virtues, a young woman discovers she is Divergent and must uncover the truth about her identity.",    
    "After the death of her father, a young girl moves to a mysterious estate where she discovers a magical garden that leads to unexpected adventures.",
    "A young boy befriends a giant robot from outer space and must protect it from government agents who want to capture it.",
    "In a world where dinosaurs roam the earth, a group of teenagers embarks on a journey to rescue their lost friend and uncover the truth about a hidden civilization.",
    "A family of superheroes must come out of retirement to save the world from a new villain threatening to destroy everything they hold dear.",
    "A group of kids discover a treasure map and embark on a perilous journey to find the hidden fortune before a group of ruthless pirates can get to it first.",    
    "A group of college students on a road trip accidentally unleash an ancient evil that threatens to consume the world.",
    "In a post-apocalyptic world, a lone survivor must navigate a dangerous landscape filled with zombies in order to find safety.",
    "A group of astronauts must find a way to survive after their spaceship crashes on a distant planet.",
    "In a future where humanity has colonized other planets, a group of rebels fights against a tyrannical government to regain their freedom.",
    "A young woman discovers she is the chosen one destined to defeat an evil sorcerer and bring peace to the land.",
    
];

module.exports.starcast = [
    ["George Clooney", "Felicity Jones", "David Oyelowo"],
    ["Gal Gadot", "Chris Pine", "Kristen Wiig"],
    ["Jamie Foxx", "Tina Fey", "Graham Norton"],
    ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
    ["Eddie Redmayne", "Alex Sharp", "Sacha Baron Cohen"],
    ["Tom Hanks", "Helena Zengel", "Michael Angelo Covino"],
    ["Rosamund Pike", "Peter Dinklage", "Eiza González"],
    ["Denzel Washington", "Rami Malek", "Jared Leto"],
    ["Gary Oldman", "Amanda Seyfried", "Lily Collins"],
    ["Viola Davis", "Chadwick Boseman", "Glynn Turman"],
    ["Carey Mulligan", "Bo Burnham", "Alison Brie"],
    ["Steven Yeun", "Yeri Han", "Alan Kim"],
    ["Vanessa Kirby", "Shia LaBeouf", "Ellen Burstyn"],
    ["Adarsh Gourav", "Rajkummar Rao", "Priyanka Chopra Jonas"],
    ["Daniel Kaluuya", "Lakeith Stanfield", "Dominique Fishback"],
    ["Riz Ahmed", "Olivia Cooke", "Paul Raci"],
    ["Tahar Rahim", "Jodie Foster", "Shailene Woodley"],
    ["Denzel Washington", "Rami Malek", "Jared Leto"],
    ["Liam Neeson", "Katheryn Winnick", "Teresa Ruiz"],
    ["Ralph Fiennes", "Gemma Arterton", "Rhys Ifans"],
    ["Ben Affleck", "Ana de Armas", "Lily Rabe"],
    ["Tom Holland", "Ciara Bravo", "Jack Reynor"],
    ["Chris Pratt", "Yvonne Strahovski", "J.K. Simmons"],
    ["Alexander Skarsgård", "Mads Mikkelsen", "Rune Temte"],
    ["Jake Gyllenhaal", "Eiza González", "Garrett Hedlund"],
    ["Chris Pine", "Thandiwe Newton", "Ben Foster"],
    ["Ryan Reynolds", "Gal Gadot", "Dwayne Johnson"],
    ["Amy Adams", "Gary Oldman", "Anthony Mackie"],
    ["Amanda Seyfried", "Lily Collins", "Tom Pelphrey"],
    ["Hugh Jackman", "Rebecca Ferguson", "Thandiwe Newton"],
    ["Tom Hardy", "Woody Harrelson", "Michelle Williams"],
    ["Andrew Garfield", "Jessica Chastain", "Vincent D'Onofrio"],
    ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    ["Keanu Reeves", "Carrie-Anne Moss", "Yahya Abdul-Mateen II"],
];
